version: "3.8"

services:
  web:
    build: .
    container_name: meu_php_container
    ports:
      - "80:80"
    volumes:
      - ./php:/var/www/html

  db:
    image: mysql:5.7
    container_name: meu_mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: lerolero411
      MYSQL_DATABASE: teste
      MYSQL_USER: bruno
      MYSQL_PASSWORD: lerolero123
    volumes:
      - mysqldata:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  mysqldata: